settings:
  # username: KevinNitroG
  commit_msg: "ğŸ“ˆ Update recent activities"
  max_lines: 10
  readme_file: "./README.md"
  disabled_events:
  url_text: "{REPO}{ID}"
  date:
    timezone: "Asia/Ho_Chi_Minh"
    text: "Last Updated on {DATE}"
    format: "dddd, d/m/yy h:mm TT"
  commit_name: "GitHub Actions"
  commit_email: "action@github.com"
  line_prefix: "{NUM}. "
  ignored_repos:
    - KevinNitrG/KevinNitroG
messages:
  comments: "ğŸ’¬ Commented on {ID} in {REPO}"
  push: "â¬†ï¸ Pushed {AMOUNT} commit(s) to {REPO}"
  issue_opened: "â—ï¸ Opened issue {ID} in {REPO}"
  issue_closed: "âœ”ï¸ Closed issue {ID} in {REPO}"
  pr_opened: "ğŸ’ª Opened PR {ID} in {REPO}"
  pr_closed: "âŒ Closed PR {ID} in {REPO}"
  pr_merged: "ğŸ‰ Merged PR {ID} in {REPO}"
  create_repo: "ğŸ“” Created new repository {REPO}"
  fork_repo: "ğŸ”± Forked {FORK} from {REPO}"
  wiki_create: "ğŸ“– Created new wiki page {WIKI} in {REPO}"
  added_member: "ğŸ¤ Became collaborator on {REPO}"
  changes_approved: "ğŸ‘ Approved {ID} in {REPO}"
  changes_requested: "ğŸ”´ Requested changes in {ID} in {REPO}"
  new_release: "âœŒï¸ Released {ID} in {REPO}"
  new_star: "â­ Starred {REPO}"